server:
  port: 8085
  servlet:
    context-path: "/"
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password: tkawk112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace